-- SELECT year AS "Year",
--           month AS"Month",
--         month_name AS "Month Name",
--         west AS "West",
--         midwest AS "Midwest",
--         south AS "South",
--         northeast AS "Northeast"
-- FROM tutorial.us_housing_units
-- LIMIT 15
 -- SELECT *
-- FROM tutorial.us_housing_units
-- WHERE
--   month = 1
 -- SELECT *
--   FROM tutorial.us_housing_units
-- WHERE south < 20
 -- SELECT *
--   FROM tutorial.us_housing_units
-- WHERE month_name <= 'N'
 -- SELECT year,
--       month,
--       west,
--       south,
--       west + south AS south_plus_west
--   FROM tutorial.us_housing_units
 -- SELECT year,
--       month,
--       west,
--       south,
--       west + south - 4 * year AS nonsense_column
--   FROM tutorial.us_housing_units

 -- SELECT  year AS "Year",
--         month AS"Month",
--         month_name AS "Month Name",
--         west AS "West",
--         midwest AS "Midwest",
--         south AS "South",
--         northeast AS "Northeast",
--         midwest + west + south + northeast AS "usa_total"
--   FROM tutorial.us_housing_units
 -- SELECT  year AS "Year",
--         month AS"Month",
--         month_name AS "Month Name",
--         (west/(west + midwest + south + northeast))*100 AS "West",
--         (midwest/(west + midwest + south + northeast))*100 AS "Midwest",
--         (south/(west + midwest + south + northeast))*100 AS "South",
--         (northeast/(west + midwest + south + northeast))*100 AS "Northeast"
--         FROM tutorial.us_housing_units
-- --   WHERE year >= 2000
 -- SELECT *
--   FROM tutorial.billboard_top_100_year_end
-- ORDER BY year DESC, year_rank
 -- SELECT *
--   FROM tutorial.billboard_top_100_year_end
-- WHERE "group" LIKE 'Snoop%'
 -- SELECT *
--   FROM tutorial.billboard_top_100_year_end
-- WHERE artist ILIKE 'dr_ke'

-- SELECT *
-- FROM tutorial.billboard_top_100_year_end
-- WHERE "group" ILIKE '%ludacris%'

-- SELECT *
-- FROM tutorial.billboard_top_100_year_end
-- WHERE "group" ILIKE 'DJ%'

-- SELECT SUM(volume)
--   FROM tutorial.aapl_historical_stock_price
